# Generated by Django 5.2.1 on 2025-06-03 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remera',
            name='genero',
            field=models.IntegerField(choices=[(1, 'Hombre'), (2, 'Mujer'), (3, 'Unisex')]),
        ),
        migrations.AlterField(
            model_name='remera',
            name='talle',
            field=models.IntegerField(choices=[(1, 'XS'), (2, 'S'), (3, 'M'), (4, 'L'), (5, 'XL'), (6, 'XXL')]),
        ),
    ]
