# Generated by Django 5.2.1 on 2025-06-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0002_alter_remera_genero_alter_remera_talle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remera',
            name='color',
            field=models.CharField(max_length=50, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='remera',
            name='genero',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Hombre'), (2, 'Mujer'), (3, 'Unisex')], verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='remera',
            name='lisa',
            field=models.BooleanField(choices=[(True, 'Si'), (False, 'No')], verbose_name='Lisa'),
        ),
        migrations.AlterField(
            model_name='remera',
            name='marca',
            field=models.CharField(max_length=50, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='remera',
            name='talle',
            field=models.PositiveSmallIntegerField(choices=[(1, 'XS'), (2, 'S'), (3, 'M'), (4, 'L'), (5, 'XL'), (6, 'XXL')], verbose_name='Talle'),
        ),
    ]
