# Generated by Django 5.2.1 on 2025-06-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0003_alter_remera_color_alter_remera_genero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remera',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='remeras/'),
        ),
    ]
